# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8b9964968a44efdca4ad80c40841399f25397f4183587cd9d546520d0d1a110e3daca05c1800012f6019fd962f9c9fe5d0bf49bb5e862b0bb7dad157002a2b7

test:
  secret_key_base: 3bf04c4fdb870d1deb44a684fb47dbd2f62dde738ba371943b9ddb5956e2fdf64176e790049daba1f9daaa9c543d86e8550050629aa657c0bbd34d6e67babc0f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
